---
# customer patch work PoC Details
- name: ansible patch work PoC Details
  hosts: category01
  gather_facts: true
  become: true

  vars_files:
    - /home/cloud_user/cusotmerx_poc/previlege_user
  vars:
    ansible_become_pass: '{{ previlege_access }}'
    mail_server: 172.31.18.243
    smtp_service_port: 25
    lock_file: /var/lock/ansible_patch_{{ ansible_date_time.date }}.lock

  pre_tasks:
    - name: This is pre_task -01
      debug:
        msg: "This is pre task no 01"
      ignore_errors: true
      tags: pretask01
      register: pretask01_response
 
    - name: This is pre_task -02
      debug:
        msg: "This is pre task no 02"
      ignore_errors: true
      tags: pretask02
      register: pretask02_response

  tasks:
    - name: Create Lock File and Send Email to Ops team about ansible patches
      block:
        - name: Create Lock file
          file:
            path: '{{ lock_file }}'
            state: touch
    
        - name: Send an email to operations about to kick off system patch work.
          mail:
            host: '{{ mail_server }}'
            port: '{{ smtp_service_port }}'
            to: Cloud User<cloud_user@[{{ ansible_default_ipv4.address }}]>
            from: Cloud User <cloud_user@{{ ansible_fqdn }}>
            subject: Ansible-patching
            body: Hello, System {{ ansible_hostname }} about to get patches from Ansible control server. Please save your work. To acknowlege this email, please remove the file {{ lock_file }} which is owned by root. If you dont remove this lock file, patches wont be applied to this host - {{ ansible_hostname }}. Thank you for your co-operation and we will inform you after the patching process completed. Thank you.
          ignore_errors: true
      when: pretask01_response.failed != true and pretask02_response.failed != true

    - name: look out for lock file
      wait_for:
        path: '{{ lock_file }}'
        state: absent
        msg: "Specified Lock File still present"
      register: remove_lockfile

    - name: apply various patches
      yum:
        name: "*"
        state: latest
      register: apply_patches
      when: remove_lockfile.failed != true
    
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot Initiated by Ansible"
      register: system_reboot
      when: apply_patches.changed == true